apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://lusoal.github.io/helm-charts-examples/'
    chart: 'python-application-chart'
    targetRevision: '0.1.0'
    helm:
      values: |
        name: demp-app
        namespace: demp-app
        replicaCount: 1
        image:
          repository: 546971145778.dkr.ecr.us-east-1.amazonaws.com/python-basic-app
          tag: "latest"
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: 80
        env:
          S3_BUCKET_NAME: 'demp-app-asdfasdf'
        serviceAccount:
          create: true
          name: python-basic-app
          iamRoleArn: arn:aws:iam::546971145778:role/demp-app-role'
  destination:
    name: "in-cluster"
    namespace: demp-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true